# Generated by Django 5.1.4 on 2026-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_question_selected_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Facile"), ("medium", "Moyen"), ("hard", "Difficile")],
                default="medium",
                help_text="Niveau de difficulté du quiz (choisi à la création).",
                max_length=10,
            ),
        ),
    ]
